apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm.yaml

helmCharts:
  - name: helm
    version: 0.1.0
    releaseName: vfls
    repo: https://vagnerfls.github.io/helm/
    additionalValuesFiles:
      - values.yaml