apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cm.yaml

helmCharts:
  - name: helm
    releaseName: helm-demo
    version: 0.1.0
    repo: https://vagnerfls.github.io/helm/