name: vfls

frontend:
  enabled: true           # Deve ser habilitado se o projeto contér a chamada frontend
  replicas: 1             # Quantidade de pods que rodará a aplicação
  containerPort: 8080     # Porta default para todos projetos
  cpuLimit: 10m           # Limite de CPU que um pod, pode utilizar. (valor default)
  cpuRequest: 10m         # Solicitação inicial de CPU para o pod. (valor default)
  memoryRequest: 32Mi     # Solicitação inicial de RAM para o pod. (valor default)
  memoryLimit: 32Mi       # Limite de RAM que um pod, pode utilizar. (valor default)
  route: true             # Dever ser habilitado quando for utilizar rota para a camada.

api:
  enabled: true           # Deve ser habilitado se o projeto contér a chamada frontend
  replicas: 1             # Quantidade de pods que rodará a aplicação
  containerPort: 8080     # Porta default para todos projetos
  cpuLimit: 10m           # Limite de CPU que um pod, pode utilizar. (valor default)
  cpuRequest: 10m         # Solicitação inicial de CPU para o pod. (valor default)
  memoryRequest: 32Mi     # Solicitação inicial de RAM para o pod. (valor default)
  memoryLimit: 32Mi       # Limite de RAM que um pod, pode utilizar. (valor default)
  route: true             # Dever ser habilitado quando for utilizar rota para a camada.  